from auth.common.domain.exceptions.base import DomainError


class InvalidDataException(DomainError):
    pass
